name: mobile
description: An e-commerce flutter application using firebase & clean architecture

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  flutter_login_facebook: ^1.0.1
  flutter_riverpod: ^0.14.0+3
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  image_cropper: ^1.4.1
  internet_connection_checker: ^0.0.1+1
  json_annotation: ^4.0.1
  path: ^1.8.0
  path_provider: ^2.0.2
  riverpod: ^0.14.0+3
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^3.0.0
  twitter_login: ^4.0.1
  font_awesome_flutter: ^9.1.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  logger: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/